### ISSUE TITLE
Re-compilation failed

### ISSUE THREAD

**Issue by ArtemX9** [johnno1962/InjectionIII#341]
Hi! I've been trying to add Injection to the project, but no luck. 
I've added the Injection as an SPM package.
Anything I do ends with the module telling me the same:

🔥 Compiling _some file_
🔥 ⚠️ Re-compilation failed (see: /Users/artem/Library/Developer/CoreSimulator/Devices/69A7A398-67F1-4568-B6B1-8A9039041E42/data/Containers/Data/Application/187AFE34-64FF-4149-862D-A866A053CBB1/tmp/command.sh)
<unknown>:0: error: cannot open file '/var/folders/kb/rvztfkq56b7bypq7nrq8h75h0000gn/T/sources-5a5041' (No such file or directory)

**For example:**
🔥 Compiling /Users/artem/Projects/tucasa/Casa/Casa/Screens/Main Screens/Streaming/StreamingViewController.swift
🔥 ⚠️ Re-compilation failed (see: /Users/artem/Library/Developer/CoreSimulator/Devices/69A7A398-67F1-4568-B6B1-8A9039041E42/data/Containers/Data/Application/187AFE34-64FF-4149-862D-A866A053CBB1/tmp/command.sh)
<unknown>:0: error: cannot open file '/var/folders/kb/rvztfkq56b7bypq7nrq8h75h0000gn/T/sources-5a5041' (No such file or directory)

**On the start it writes to console** 
🔥 HotReloading connected /Users/artem/Projects/tucasa/Casa/Casa.xcodeproj
🔥 Watching files under /Users/artem/Projects/tucasa/Casa
<img width="659" alt="Снимок экрана 2021-08-18 в 20 55 37" src="https://user-images.githubusercontent.com/12211483/129948349-6230bba7-f3bf-4db7-b4e0-a55beb781b91.png">
<img width="773" alt="Снимок экрана 2021-08-18 в 20 55 46" src="https://user-images.githubusercontent.com/12211483/129948351-9a022cf2-06ba-480c-b0e8-c40b566c8f90.png">
<img width="681" alt="Снимок экрана 2021-08-18 в 20 58 07" src="https://user-images.githubusercontent.com/12211483/129948529-15d60b1a-0b3a-488d-a910-d2f8ae831dff.png">

**Comment by johnno1962** [comment]
Hi, looks like a quoting problem due to a space in a filename. Are you able to post the file /Users/artem/Library/Developer/CoreSimulator/Devices/69A7A398-67F1-4568-B6B1-8A9039041E42/data/Containers/Data/Application/187AFE34-64FF-4149-862D-A866A053CBB1/tmp/command.sh or email it to me at github @ johnholdsworth.com

**Comment by ArtemX9** [comment]
[command.txt](https://github.com/johnno1962/InjectionIII/files/7009267/command.txt)
just changed the extension to .txt from .sh since GitHub didn't allow me to post it =/

**Comment by johnno1962** [comment]
Thanks for that. Which version of Xcode is this? I looks like either you project has too many files in a target or you have "Whole module optimisation" turned on which InjectionIII doesn't support.

**Comment by ArtemX9** [comment]
It's Version 12.5.1 (12E507)
<img width="165" alt="Снимок экрана 2021-08-18 в 22 26 00" src="https://user-images.githubusercontent.com/12211483/129959770-c8f3c678-b5ae-4a3c-bb6d-cc90c7ad1cc5.png">
<img width="710" alt="Снимок экрана 2021-08-18 в 22 29 22" src="https://user-images.githubusercontent.com/12211483/129960231-822ce547-eb18-49e8-97ba-0dffcddd96f3.png">

**Comment by johnno1962** [comment]
How many Swift files are compiled in the target containing the file you are trying to inject? (You can see this on the build phases tab).

**Comment by ArtemX9** [comment]
Oh, I see. It's 332 items for Compile sources 23 items for Link Binary With Libraries.  :)

**Comment by johnno1962** [comment]
I'm afraid that could exceed the capabilities of injection unless you can break you project into frameworks which might be a good idea in it's own right. Newer versions of Xcode create this -filelist file but unfortunately deletes it afterwards so you can't use the same command from the logs to rebuild a class individually. I'll file a radar and see if they can remove the deterring of the file which could be a small change for them.

**Comment by johnno1962** [comment]
Could you export a build log for your project and email it to me. We used to have a solution for large numbers of files but something has changed in Xcode fairly recently and it has stopped working.

**Comment by ArtemX9** [comment]
Thank you. As of right now we don't have a capacity for switching to micro services architecture, however we recently started working towards it, but it definitely won't happen any time soon.
Yep, I'll send you an email with build log, but probably tomorrow, is that ok?

**Comment by ArtemX9** [comment]
I really appreciate time you spent trying to help me, thank you once again!

**Comment by johnno1962** [comment]
Not a problem. It's very useful when people report problems. I've checked with a test project I have with 530 source files and it works so it could be something to do with quoting and the spaces directory names in your project. I'd appreciate it if you send though the project log (Export... button on the build log). It could be something fixable.

**Comment by ArtemX9** [comment]
Great news! I've just sent you the log to your email.

**Comment by johnno1962** [comment]
Thanks! It's a quoting issue due to a naive regex and fixable. A new release of injection with this resolved should be available tomorrow for you.

**Comment by ArtemX9** [comment]
Wow, that's awesome!

**Comment by ArtemX9** [comment]
I'm looking forward to test it :)

**Comment by johnno1962** [comment]
It was a one character change; These pesky regexes. New version of InjectionIII 2.9.3 uploaded but since you're using the HotReloading Swift package you should just need to update to version 1.9.3

**Comment by ArtemX9** [comment]
Great news! It started working, but in some cases I have an app crashing:
<img width="929" alt="Снимок экрана 2021-08-19 в 15 39 54" src="https://user-images.githubusercontent.com/12211483/130069855-0808155d-89ed-4d61-9d58-6a5bc0c4ea07.png">

**Comment by johnno1962** [comment]
That's an odd crash which should just be doing a pointer comparison. I've pushed a commit 2e99410166f5008c00d0c6ce4f65e88dfd0c0301 which changes it to ==. Can you update and try it out? I may remove that code altogether.

**Comment by johnno1962** [comment]
I can TeamView to investigate this if that is possible for you. If so, send details to my email address.

**Comment by ArtemX9** [comment]
Updated to that commit, but now it fails abit further, but still fails:
<img width="940" alt="Снимок экрана 2021-08-19 в 18 19 06" src="https://user-images.githubusercontent.com/12211483/130095319-127f361b-35b2-4fbc-9df2-6b1dff33b127.png">
Yep, we can TeamView :)

**Comment by johnno1962** [comment]
Not entirely surprising. The moment I receive your TeamView coords, I'll connect and ew'll get to the bottom of this. Is it always the same source file that crashes?

**Comment by ArtemX9** [comment]
I've just sent them to your email, please check if they work for you. 
Yep, I was trying making the UI change by just replacing the constant value and it crashed and continues crashing :)

**Comment by johnno1962** [comment]
Hi Artem,

I’ve pushed an amend to HotReloading e6c91d36301ebd7cbe6f0d4f7d7fb5ea665e5ba1 
which resolves the generic superclass problem which I was able to replicate this end. This
change is probably going to benefit a lot of users so thanks for taking the time to report it!
Please re-clone your ~/HotReloading, try a few injections and see how things are looking now.

Email me when you have some time for the hunt to find what exactly about your "presenting" 
code path is causing the problem we saw today so we can either resolve or document it.

Thanks,

John

**Comment by ArtemX9** [comment]
Thanks, John! 
One more thing about that class: we use web sockets connection in it, can this be related?

**Comment by johnno1962** [comment]
No Problem, How are you thinking it could affect it? Because HotReloading
uses a socket to connect to its server? Shouldn’t be a problems as it uses
the very low level bsd sockets api.

I’m spending some time on supporting generics today and its nearly there
but don’t want to release it just yet. As I say, experiment with what you can
and can’t inject and we can work through where there are issues some time.

Cheers,

John
