### ISSUE TITLE
InjectionIII cannot take effect when using the SweetPad extension for debugging in Cursor

### ISSUE THREAD

**Issue by iamnanyi** [johnno1962/InjectionIII#542]
My Environment:
- macOS: 15.3.1
- Xcode: 16.2
- InjectionIII: 5.0.6
- Project: Primarily using SwiftUI

Cases Where InjectionIII Works Normally:
- Running the simulator in Xcode
- Running on a physical device in Xcode
- Running the simulator in Cursor (non-Debug mode)
- Running on a physical device in Cursor (non-Debug mode)
- Running the simulator in Cursor (Debug mode)

Problematic Case:
- Running on a physical device in Cursor (Debug mode)

Error When Modifying UI in Debug Mode on a Physical Device:
💉 Compiling /Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/User/SignInPage.swift
💉 Compiling /Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/User/SignInPage.swift
💉 ⚠️ Re-compilation failed (see: /var/folders/x5/fxwqr6j93p57qtmbgf9qh0500000gp/T/command.sh)
<unknown>:0: error: stat cache file '/Users/username/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.2-22C146-d5b9239ec3bf5b3adbecdf21472871e3.sdkstatcache' not found
<unknown>:0: error: stat cache file '/Users/username/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.2-22C146-d5b9239ec3bf5b3adbecdf21472871e3.sdkstatcache' not found

Additional Information:
- I tried using InjectionNext, but modifying the UI in both Xcode and Cursor Debug mode causes the app to crash, so I reverted to InjectionIII.
- The only remaining issue is modifying the UI in Cursor Debug mode on a physical device.

I would appreciate your help in resolving this issue.

**Comment by iamnanyi** [comment]
> Hi, this is an unusual, interesting that is should only fail for one platform. I've uploaded a new release candidate that filters out this problematic option https://github.com/johnno1962/InjectionIII/releases/tag/5.0.7RC1 if you want to give it a try.
> 
> When you said when you tried InjectionNext it crashed did you mean your app or the InjectionNext.app itself?

I used version 5.0.7 RC1 and ran the Debug on a real device in Cursor. After modifying the UI code, it still reports an error:
💉 Compiling /Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/Pro/ProPage.swift
💉 ⚠️ Could not locate compile command for "/Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/Pro/ProPage.swift" in /Users/username/Library/Developer/Xcode/DerivedData/TalkEasy-heajtjrpioiaejdtuokqpmaeuvqq/Logs/Build/.
This could be due to one of the following:
1. Injection does not work with Whole Module Optimization.
2. There are restrictions on characters allowed in paths.
3. File paths in the simulator are case sensitive.
4. The modified source file is not in the current project.
5. The source file is an XCTest that has not been run yet.
6. Xcode has removed the build logs. Edit a file and re-run
or try a build clean then rebuild to make logs available or
consult: "/var/folders/x5/fxwqr6j93p57qtmbgf9qh0500000gp/T/command.sh". Whatever the problem, if you see
this error it may be worth trying the new implementation
https://github.com/johnno1962/InjectionNext.
💉 ⚠️ Recompilation failing, are you renaming/adding files? Build your project to generate a new Xcode build log and try injecting again or relauch your app.

When I use InjectionNext, my app crashes.

**Comment by iamnanyi** [comment]
I tried to move the project to the ~/ directory, but the problem still cannot be resolved. The two errors mentioned above may occur alternately.
When I switched to InjectionNext, there was no available stack information at the crash breakpoint, and I couldn't find any clues to feedback.

**Comment by johnno1962** [comment]
It is possible the first error is stuck in a cache somewhere as that should be fixed. Can you try introducing a syntax error into your code, injecting it, seeing it fail and then removing the change and trying again. I don't know why you would be seeing the second error other than the general advice it gives. The way forward I InjectionNext though, any screen shots or stack traces you can provide would be helpful there.

**Comment by iamnanyi** [comment]
I previously set .enableInjection() only in my xxxApp.swift when using InjectionIII, and it worked fine when modifying a secondary page in the App running in Xcode or non-debug Cursor, but it caused an error only in the real device debug Cursor.
Then I tried to add .enableInjection() to the page I want to modify in InjectionNext, so that when I modify the page content, it no longer crashes (I'm not sure if it's because of this reason).
The current situation is that InjectionIII behaves exactly the same as InjectionNext, but it fails to refresh the page successfully only when using the Cursor extension for debugging on a real device.
InjectionIII is still reporting an error:
💉 Compiling /Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/User/SignInPage.swift
💉 Compiling /Users/username/Documents/Workspace/AiPuWeiLai/TalkEasy/TalkEasy/TalkEasy/Business/Pages/User/SignInPage.swift
💉 ⚠️ Re-compilation failed (see: /var/folders/x5/fxwqr6j93p57qtmbgf9qh0500000gp/T/command.sh)
:0: error: stat cache file '/Users/username/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.2-22C146-d5b9239ec3bf5b3adbecdf21472871e3.sdkstatcache' not found
:0: error: stat cache file '/Users/username/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos18.2-22C146-d5b9239ec3bf5b3adbecdf21472871e3.sdkstatcache' not found

And I checked the last error for InjectionNext, and the content is:
ld: warning: search path '/Applications/InjectionNext.app/Contents/Frameworks' not found
ld: warning: search path '/Applications/InjectionNext.app/Contents/Frameworks' not found
ld: building for 'macOS', but linking in object file (/private/tmp/injectionNext_0.o) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Currently, when switching tools, I have only modified the content of Run Script, and all other configurations are the same.

**Comment by iamnanyi** [comment]
Sorry, I'll correct this, my InjectionNext is fine now, but there is still an issue with InjectionIII.
I want to ask if it is necessary to add the following code to each SwiftUI code.
#if DEBUG
@exported import Inject
#endif

#if DEBUG
@ObserveInjection var redraw
#endif

#if DEBUG
.enableInjection()
#endif

**Comment by johnno1962** [comment]
You can't just add .enableInjection() at the top level it needs to be added to any view you want to be able to inject. If things are not redrawing you also need to add `@ObserveInjection var redraw` to each view you want to be able to refresh on injection. Re: InjectionIII, can you send the contents of the file e.g. /var/folders/x5/fxwqr6j93p57qtmbgf9qh0500000gp/T/command.sh it mentions to GitHub at johnholdsworth dot com and I can try to make out what's going on. 
P.S. I see you've just replied. Yes, all that code is necessary to erase the SwiftUI.View return type and have views refresh.

**Comment by johnno1962** [comment]
> Currently, when switching tools, I have only modified the content of Run Script, and all other configurations are the same.
This is the right ways to do it along with stoping starting the InjectionNext/InjectionIII apps.

**Comment by johnno1962** [comment]
Thanks, I managed to find that the fix I put into 5.0.7 wasn't working and have updated the release candidate (build number 8169 now). Can you try that please?

**Comment by iamnanyi** [comment]
I downloaded the latest InjectionIII from https://github.com/johnno1962/InjectionIII/releases/tag/5.0.7RC1, and it works normally! Thank you so much for your patient guidance.

**Comment by johnno1962** [comment]
Hurrah! Thanks for _your_ patience. Close this when you feel you're happy with things.
